# Generated by Django 4.0.3 on 2022-03-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owegoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
    ]
