# Generated by Django 4.0.3 on 2022-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owegoapi', '0007_remove_bill_note_note_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='bill_tag',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_tag',
            field=models.ManyToManyField(related_name='tags', to='owegoapi.tag'),
        ),
    ]
