# Generated by Django 4.0.3 on 2022-03-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owegoapi', '0008_remove_tag_bill_tag_bill_bill_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owegoapi.tag', verbose_name='Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_tag',
            field=models.ManyToManyField(related_name='tags', to='owegoapi.billtag'),
        ),
    ]
