# Generated by Django 4.0.3 on 2022-03-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owegoapi', '0009_billtag_alter_bill_bill_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billtag',
            old_name='bill',
            new_name='tag',
        ),
    ]
