# Generated by Django 4.0.3 on 2022-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owegoapi', '0011_alter_note_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
